language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "kU8pPpycrd2OjZuTiGaDUFnAfsfuv0tGuXsBMYXzR44vK2BHeZZM6rdvMb41jLvfZG9+/6FsAY0IHg0N9Jdx/MBoSeb6dJ2X9UFjZvvhrQPwroBSC35j1FllrO3uEq6Smnsw4DRKMYCKLZmBCME3Oyn2a5D1gLYU5/9qVoMmEsRP30sXd3E88T43LwWF+Ovg0e0qLrHlhuQknWJELZ4VrsrW9ieLaDI9QL7killndAzrDQFedi9GjO7oeIrzBHGkzPNkPvreBZ+x0aIBBKszHluaJgfNSJW0VpZEezb6nESvtxyQngtJy1B19z5jT3LydF6fLCZHGg2DtmW2Oa9np3+SCTuZ7VCALouWAicSgH5e72mL584wmB6CaxVPYvnBz0LEDlZm5Qkhu4Vd5KPYVnvgsyJjB00D9YOWHuV10Q7AUYNp8KgnOwdmRo8AzvS25HfLFEwqmlNeFT2JonpwNzV95fKNX3OuvLgbGGc1JIg3OncQG8HUABvaqB/tRb0WA2kdKRD1mbREUVA8HFY1Ahr4nB4bs9D3Z4yfNHXHDn1qYjYyukNZ6BE/IB2hjE8bRINfEDSoOieWLhhHIDjwHkjKtGrR8cI4FW3xcJOSF0TlWIPo3w2ati44+472tETwg2RW3/zRZWIV7f/7kbQ5+aOLkbcrhR3ci0T+l/+obcs="
env:
  secure: "JklWaIB984WBtqB1d+aaYVt+vKxESyErGVqeqOgaxqcPyjYfHnJP2e8J8ndKgCJY/RAycm7AZ+xwpth9ho4WltC7/6n4qRHKKS78W+l8WvSR3EMgRs8g24aobMlsWeWgb8OrkwCUacr4wBendfmy8et/UhcwhZwtyp2Wf/DRjyewjM5lIhf+QOgR9RCpnReZl1kscTqfID1aJ5rMMj803C5vBrHvcIwX1HucJBvrz13Box7C+vTjYJxsRU6AyOGGQ74mHMrZRX48MBDIq+rUslrOJ8+bFC/M6OJKZhPk8l80HQevX9Z8zztPo8K+Fv389duocXRqKtv09rIPGP6Cox4W087XynjaiMlExnrifW1BR68StmaMwGP4DuCjFKwlCsEUo33iUZpkmFn++IjVGzu6aE4QRWG5QpyNaw+9AVnnoq1l1OZ2GAwZLzzHnyN0Dqjxy7cIKLLj0//rZLTQQQEnO3gBf/JWl5x3uSfIsyJR0g7dofDVUNvvuyZst3U39Sg2U23zBl7u2PfEkleX43v8Q2M2Hz0wBYUXH3YIWOMgRldhuRe4V1tCGV5HIvGpkr22CxgvqBHQHnW6y8GEP9IxrIdSMWYnUvBTHNt4tCtYbNVtalu3etEy73zoF/fSghin+A3uh1ar3YhKkMouVevVOzIzYWM8b2PSK6ivMSE="
